#!/bin/bash
#SBATCH --job-name=wifi-train
#SBATCH --output=logs/embeddings_output_%j.out  
#SBATCH --error=logs/embeddings_error_%j.err
#SBATCH --mem=120G                             


# Go to project directory
cd /common/users/oi66/Wifi-Fingerprinting

# Activate your virtual environment
source CNN_venv/bin/activate

# (Optional) Ensure TF32 is allowed via environment (for reproducibility)
export NVIDIA_TF32_OVERRIDE=1

# Run your script
python3 main.py
